//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Inputs/InputSystem_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Inputs/InputSystem_Actions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @InputSystem_Actions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @InputSystem_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputSystem_Actions"",
    ""maps"": [
        {
            ""name"": ""Players"",
            ""id"": ""e89c9497-a87b-4751-9547-2de3a37e8dcd"",
            ""actions"": [
                {
                    ""name"": ""Test"",
                    ""type"": ""Button"",
                    ""id"": ""4c18cbcd-4071-45c4-b3d9-db01d69e2437"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LMov"",
                    ""type"": ""Value"",
                    ""id"": ""20ea0637-4edc-4535-bdf7-1b27c4dfd8be"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RMov"",
                    ""type"": ""Value"",
                    ""id"": ""8e9fa565-f786-4fa0-ab21-9bc25429ad6d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EjeX"",
                    ""type"": ""Value"",
                    ""id"": ""8a4c97ae-b922-4ddf-87c5-e4d66bdfed9c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EjeY"",
                    ""type"": ""Value"",
                    ""id"": ""0cc14b8d-4cb4-440b-a372-f97d9120b734"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LUp"",
                    ""type"": ""Button"",
                    ""id"": ""96240422-0ada-4945-86d3-d2b989f4e074"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LLeft"",
                    ""type"": ""Button"",
                    ""id"": ""74688b4a-44fe-4d52-80b6-fb1ddbe07a2b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LDown"",
                    ""type"": ""Button"",
                    ""id"": ""94c7cbd9-8e7d-44eb-8f71-8c176fdf729e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LRight"",
                    ""type"": ""Button"",
                    ""id"": ""d6e61272-8fbd-4447-bb71-8c0f92ab0603"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RUp"",
                    ""type"": ""Button"",
                    ""id"": ""3c4d5183-2eee-453f-879c-4fe6429cc579"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RLeft"",
                    ""type"": ""Button"",
                    ""id"": ""55a09362-948d-46f5-aedd-30128b45876b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RDown"",
                    ""type"": ""Button"",
                    ""id"": ""7cbedfae-1c14-4411-9e09-cc43871ce6bd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RRight"",
                    ""type"": ""Button"",
                    ""id"": ""94d73eef-ca00-4856-9a54-5c85a138d957"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LUpHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""e1f74bba-940c-4c08-8692-43d388088048"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LLeftHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""e482dcad-0113-46d5-a67d-17f060666fb1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LDownHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""70bc7e18-31dc-40d0-a09e-1a4a3dd1492a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LRightHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""08434e2a-72ad-4b1c-9489-80f06ea3d938"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RUpHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""7870dd39-f173-4325-9114-d5f929681354"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RLeftHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""523b5c7b-74d9-4296-8a36-a5362c5c0476"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RDownHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""edfa0978-2727-4196-a258-7cff8aa8da32"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RRightHoldable"",
                    ""type"": ""Button"",
                    ""id"": ""01e8147e-f12a-42b0-ad9f-f1f13ac462e0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LClick"",
                    ""type"": ""Button"",
                    ""id"": ""26d52014-b218-41c6-904f-de9562153f33"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Space"",
                    ""type"": ""Button"",
                    ""id"": ""fcd892d8-6075-42fa-a4cf-f7bbfc2b5444"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""0e9e1148-8c08-4c7f-bf87-9548ea718deb"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LMov"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""43a6c3ca-d339-4b66-a710-8c633d59e3d2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""47905a26-01f1-4182-b18d-c36576d177b1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1ab3adc7-fc8d-4897-aa94-b71a4a84cde8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""158fd753-ac52-43f5-acae-ab135b97fe56"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""51b8b3f8-993c-4c74-b0db-1f2e7c018da5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""LMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12c5dac5-0a10-4f0e-ba48-2f9ea2a6ad19"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""RMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ARROW"",
                    ""id"": ""38a27927-560f-4b4f-a2ea-722d5300743b"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RMov"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0d50afdb-fd6e-4a35-a984-2c2439b69302"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""59614f8c-2d26-4a97-a0e2-e3eb0d96aca6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""708b84a6-99d9-486f-a493-ecc1a0940a2f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""89a50741-9150-4115-aa0c-4435e7892abf"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RMov"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""1ce456f6-4c0a-4e87-932f-7f89bd222ed9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EjeX"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""078f3e4a-42e8-444b-a674-ada2b39b1a85"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""EjeX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""09608a3e-0399-4923-9101-c3fbad1e1ece"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""EjeX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""915f7d3f-da56-459b-959e-f8608a7012ae"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EjeY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a6e449a0-53c1-4164-9ae4-c04dd545bd2a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""EjeY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""d5f86732-b517-46a4-a2cf-b98ab49b9bb3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""EjeY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8e2f3aec-53a7-4dc7-9c35-8363cbe1814e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1b727d0-bf70-46df-a39b-48a3168986c7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LUpHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92a71779-e348-4eb3-bd59-8cbf35c551e5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5b0f578-a5fd-4cdc-b259-bc7bdf6b8597"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""LLeftHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7f28e53-0022-454c-9b78-97dcf17cb4b5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6038ad3-315a-438d-9421-f35d306b4454"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfe4b586-b185-4149-b7ce-ab246a63ae8d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LDownHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520a0831-5e97-4a8d-b9cf-626b19ba2555"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d76e862-c7e5-457f-b6ee-e5964266c0d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LRightHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b641d081-38e9-42ee-90aa-0fb7576a7da8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99a8c870-293a-44ef-93b3-dd11b0e979fb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RUpHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c16cf117-fe63-405f-aae8-89766c4d2ff8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43f429f3-8590-4f70-a35d-1307738f2782"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RLeftHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffac1666-fbc0-4dba-a22c-26f31858c9ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6a9dabf-ea33-4b05-9971-7b79138f302a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RDownHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfde4adb-3e54-4e61-8a47-c6444a563de0"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""753ceec6-2519-4988-b804-63e0c2e0a788"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RRightHoldable"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c23bc55-4ab0-4072-9954-ac10778c042e"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45afe49c-6f1d-452d-afc4-685ff3720fca"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Space"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Players
        m_Players = asset.FindActionMap("Players", throwIfNotFound: true);
        m_Players_Test = m_Players.FindAction("Test", throwIfNotFound: true);
        m_Players_LMov = m_Players.FindAction("LMov", throwIfNotFound: true);
        m_Players_RMov = m_Players.FindAction("RMov", throwIfNotFound: true);
        m_Players_EjeX = m_Players.FindAction("EjeX", throwIfNotFound: true);
        m_Players_EjeY = m_Players.FindAction("EjeY", throwIfNotFound: true);
        m_Players_LUp = m_Players.FindAction("LUp", throwIfNotFound: true);
        m_Players_LLeft = m_Players.FindAction("LLeft", throwIfNotFound: true);
        m_Players_LDown = m_Players.FindAction("LDown", throwIfNotFound: true);
        m_Players_LRight = m_Players.FindAction("LRight", throwIfNotFound: true);
        m_Players_RUp = m_Players.FindAction("RUp", throwIfNotFound: true);
        m_Players_RLeft = m_Players.FindAction("RLeft", throwIfNotFound: true);
        m_Players_RDown = m_Players.FindAction("RDown", throwIfNotFound: true);
        m_Players_RRight = m_Players.FindAction("RRight", throwIfNotFound: true);
        m_Players_LUpHoldable = m_Players.FindAction("LUpHoldable", throwIfNotFound: true);
        m_Players_LLeftHoldable = m_Players.FindAction("LLeftHoldable", throwIfNotFound: true);
        m_Players_LDownHoldable = m_Players.FindAction("LDownHoldable", throwIfNotFound: true);
        m_Players_LRightHoldable = m_Players.FindAction("LRightHoldable", throwIfNotFound: true);
        m_Players_RUpHoldable = m_Players.FindAction("RUpHoldable", throwIfNotFound: true);
        m_Players_RLeftHoldable = m_Players.FindAction("RLeftHoldable", throwIfNotFound: true);
        m_Players_RDownHoldable = m_Players.FindAction("RDownHoldable", throwIfNotFound: true);
        m_Players_RRightHoldable = m_Players.FindAction("RRightHoldable", throwIfNotFound: true);
        m_Players_LClick = m_Players.FindAction("LClick", throwIfNotFound: true);
        m_Players_Space = m_Players.FindAction("Space", throwIfNotFound: true);
    }

    ~@InputSystem_Actions()
    {
        UnityEngine.Debug.Assert(!m_Players.enabled, "This will cause a leak and performance issues, InputSystem_Actions.Players.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Players
    private readonly InputActionMap m_Players;
    private List<IPlayersActions> m_PlayersActionsCallbackInterfaces = new List<IPlayersActions>();
    private readonly InputAction m_Players_Test;
    private readonly InputAction m_Players_LMov;
    private readonly InputAction m_Players_RMov;
    private readonly InputAction m_Players_EjeX;
    private readonly InputAction m_Players_EjeY;
    private readonly InputAction m_Players_LUp;
    private readonly InputAction m_Players_LLeft;
    private readonly InputAction m_Players_LDown;
    private readonly InputAction m_Players_LRight;
    private readonly InputAction m_Players_RUp;
    private readonly InputAction m_Players_RLeft;
    private readonly InputAction m_Players_RDown;
    private readonly InputAction m_Players_RRight;
    private readonly InputAction m_Players_LUpHoldable;
    private readonly InputAction m_Players_LLeftHoldable;
    private readonly InputAction m_Players_LDownHoldable;
    private readonly InputAction m_Players_LRightHoldable;
    private readonly InputAction m_Players_RUpHoldable;
    private readonly InputAction m_Players_RLeftHoldable;
    private readonly InputAction m_Players_RDownHoldable;
    private readonly InputAction m_Players_RRightHoldable;
    private readonly InputAction m_Players_LClick;
    private readonly InputAction m_Players_Space;
    /// <summary>
    /// Provides access to input actions defined in input action map "Players".
    /// </summary>
    public struct PlayersActions
    {
        private @InputSystem_Actions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayersActions(@InputSystem_Actions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Players/Test".
        /// </summary>
        public InputAction @Test => m_Wrapper.m_Players_Test;
        /// <summary>
        /// Provides access to the underlying input action "Players/LMov".
        /// </summary>
        public InputAction @LMov => m_Wrapper.m_Players_LMov;
        /// <summary>
        /// Provides access to the underlying input action "Players/RMov".
        /// </summary>
        public InputAction @RMov => m_Wrapper.m_Players_RMov;
        /// <summary>
        /// Provides access to the underlying input action "Players/EjeX".
        /// </summary>
        public InputAction @EjeX => m_Wrapper.m_Players_EjeX;
        /// <summary>
        /// Provides access to the underlying input action "Players/EjeY".
        /// </summary>
        public InputAction @EjeY => m_Wrapper.m_Players_EjeY;
        /// <summary>
        /// Provides access to the underlying input action "Players/LUp".
        /// </summary>
        public InputAction @LUp => m_Wrapper.m_Players_LUp;
        /// <summary>
        /// Provides access to the underlying input action "Players/LLeft".
        /// </summary>
        public InputAction @LLeft => m_Wrapper.m_Players_LLeft;
        /// <summary>
        /// Provides access to the underlying input action "Players/LDown".
        /// </summary>
        public InputAction @LDown => m_Wrapper.m_Players_LDown;
        /// <summary>
        /// Provides access to the underlying input action "Players/LRight".
        /// </summary>
        public InputAction @LRight => m_Wrapper.m_Players_LRight;
        /// <summary>
        /// Provides access to the underlying input action "Players/RUp".
        /// </summary>
        public InputAction @RUp => m_Wrapper.m_Players_RUp;
        /// <summary>
        /// Provides access to the underlying input action "Players/RLeft".
        /// </summary>
        public InputAction @RLeft => m_Wrapper.m_Players_RLeft;
        /// <summary>
        /// Provides access to the underlying input action "Players/RDown".
        /// </summary>
        public InputAction @RDown => m_Wrapper.m_Players_RDown;
        /// <summary>
        /// Provides access to the underlying input action "Players/RRight".
        /// </summary>
        public InputAction @RRight => m_Wrapper.m_Players_RRight;
        /// <summary>
        /// Provides access to the underlying input action "Players/LUpHoldable".
        /// </summary>
        public InputAction @LUpHoldable => m_Wrapper.m_Players_LUpHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/LLeftHoldable".
        /// </summary>
        public InputAction @LLeftHoldable => m_Wrapper.m_Players_LLeftHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/LDownHoldable".
        /// </summary>
        public InputAction @LDownHoldable => m_Wrapper.m_Players_LDownHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/LRightHoldable".
        /// </summary>
        public InputAction @LRightHoldable => m_Wrapper.m_Players_LRightHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/RUpHoldable".
        /// </summary>
        public InputAction @RUpHoldable => m_Wrapper.m_Players_RUpHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/RLeftHoldable".
        /// </summary>
        public InputAction @RLeftHoldable => m_Wrapper.m_Players_RLeftHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/RDownHoldable".
        /// </summary>
        public InputAction @RDownHoldable => m_Wrapper.m_Players_RDownHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/RRightHoldable".
        /// </summary>
        public InputAction @RRightHoldable => m_Wrapper.m_Players_RRightHoldable;
        /// <summary>
        /// Provides access to the underlying input action "Players/LClick".
        /// </summary>
        public InputAction @LClick => m_Wrapper.m_Players_LClick;
        /// <summary>
        /// Provides access to the underlying input action "Players/Space".
        /// </summary>
        public InputAction @Space => m_Wrapper.m_Players_Space;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Players; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayersActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayersActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayersActions" />
        public void AddCallbacks(IPlayersActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayersActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayersActionsCallbackInterfaces.Add(instance);
            @Test.started += instance.OnTest;
            @Test.performed += instance.OnTest;
            @Test.canceled += instance.OnTest;
            @LMov.started += instance.OnLMov;
            @LMov.performed += instance.OnLMov;
            @LMov.canceled += instance.OnLMov;
            @RMov.started += instance.OnRMov;
            @RMov.performed += instance.OnRMov;
            @RMov.canceled += instance.OnRMov;
            @EjeX.started += instance.OnEjeX;
            @EjeX.performed += instance.OnEjeX;
            @EjeX.canceled += instance.OnEjeX;
            @EjeY.started += instance.OnEjeY;
            @EjeY.performed += instance.OnEjeY;
            @EjeY.canceled += instance.OnEjeY;
            @LUp.started += instance.OnLUp;
            @LUp.performed += instance.OnLUp;
            @LUp.canceled += instance.OnLUp;
            @LLeft.started += instance.OnLLeft;
            @LLeft.performed += instance.OnLLeft;
            @LLeft.canceled += instance.OnLLeft;
            @LDown.started += instance.OnLDown;
            @LDown.performed += instance.OnLDown;
            @LDown.canceled += instance.OnLDown;
            @LRight.started += instance.OnLRight;
            @LRight.performed += instance.OnLRight;
            @LRight.canceled += instance.OnLRight;
            @RUp.started += instance.OnRUp;
            @RUp.performed += instance.OnRUp;
            @RUp.canceled += instance.OnRUp;
            @RLeft.started += instance.OnRLeft;
            @RLeft.performed += instance.OnRLeft;
            @RLeft.canceled += instance.OnRLeft;
            @RDown.started += instance.OnRDown;
            @RDown.performed += instance.OnRDown;
            @RDown.canceled += instance.OnRDown;
            @RRight.started += instance.OnRRight;
            @RRight.performed += instance.OnRRight;
            @RRight.canceled += instance.OnRRight;
            @LUpHoldable.started += instance.OnLUpHoldable;
            @LUpHoldable.performed += instance.OnLUpHoldable;
            @LUpHoldable.canceled += instance.OnLUpHoldable;
            @LLeftHoldable.started += instance.OnLLeftHoldable;
            @LLeftHoldable.performed += instance.OnLLeftHoldable;
            @LLeftHoldable.canceled += instance.OnLLeftHoldable;
            @LDownHoldable.started += instance.OnLDownHoldable;
            @LDownHoldable.performed += instance.OnLDownHoldable;
            @LDownHoldable.canceled += instance.OnLDownHoldable;
            @LRightHoldable.started += instance.OnLRightHoldable;
            @LRightHoldable.performed += instance.OnLRightHoldable;
            @LRightHoldable.canceled += instance.OnLRightHoldable;
            @RUpHoldable.started += instance.OnRUpHoldable;
            @RUpHoldable.performed += instance.OnRUpHoldable;
            @RUpHoldable.canceled += instance.OnRUpHoldable;
            @RLeftHoldable.started += instance.OnRLeftHoldable;
            @RLeftHoldable.performed += instance.OnRLeftHoldable;
            @RLeftHoldable.canceled += instance.OnRLeftHoldable;
            @RDownHoldable.started += instance.OnRDownHoldable;
            @RDownHoldable.performed += instance.OnRDownHoldable;
            @RDownHoldable.canceled += instance.OnRDownHoldable;
            @RRightHoldable.started += instance.OnRRightHoldable;
            @RRightHoldable.performed += instance.OnRRightHoldable;
            @RRightHoldable.canceled += instance.OnRRightHoldable;
            @LClick.started += instance.OnLClick;
            @LClick.performed += instance.OnLClick;
            @LClick.canceled += instance.OnLClick;
            @Space.started += instance.OnSpace;
            @Space.performed += instance.OnSpace;
            @Space.canceled += instance.OnSpace;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayersActions" />
        private void UnregisterCallbacks(IPlayersActions instance)
        {
            @Test.started -= instance.OnTest;
            @Test.performed -= instance.OnTest;
            @Test.canceled -= instance.OnTest;
            @LMov.started -= instance.OnLMov;
            @LMov.performed -= instance.OnLMov;
            @LMov.canceled -= instance.OnLMov;
            @RMov.started -= instance.OnRMov;
            @RMov.performed -= instance.OnRMov;
            @RMov.canceled -= instance.OnRMov;
            @EjeX.started -= instance.OnEjeX;
            @EjeX.performed -= instance.OnEjeX;
            @EjeX.canceled -= instance.OnEjeX;
            @EjeY.started -= instance.OnEjeY;
            @EjeY.performed -= instance.OnEjeY;
            @EjeY.canceled -= instance.OnEjeY;
            @LUp.started -= instance.OnLUp;
            @LUp.performed -= instance.OnLUp;
            @LUp.canceled -= instance.OnLUp;
            @LLeft.started -= instance.OnLLeft;
            @LLeft.performed -= instance.OnLLeft;
            @LLeft.canceled -= instance.OnLLeft;
            @LDown.started -= instance.OnLDown;
            @LDown.performed -= instance.OnLDown;
            @LDown.canceled -= instance.OnLDown;
            @LRight.started -= instance.OnLRight;
            @LRight.performed -= instance.OnLRight;
            @LRight.canceled -= instance.OnLRight;
            @RUp.started -= instance.OnRUp;
            @RUp.performed -= instance.OnRUp;
            @RUp.canceled -= instance.OnRUp;
            @RLeft.started -= instance.OnRLeft;
            @RLeft.performed -= instance.OnRLeft;
            @RLeft.canceled -= instance.OnRLeft;
            @RDown.started -= instance.OnRDown;
            @RDown.performed -= instance.OnRDown;
            @RDown.canceled -= instance.OnRDown;
            @RRight.started -= instance.OnRRight;
            @RRight.performed -= instance.OnRRight;
            @RRight.canceled -= instance.OnRRight;
            @LUpHoldable.started -= instance.OnLUpHoldable;
            @LUpHoldable.performed -= instance.OnLUpHoldable;
            @LUpHoldable.canceled -= instance.OnLUpHoldable;
            @LLeftHoldable.started -= instance.OnLLeftHoldable;
            @LLeftHoldable.performed -= instance.OnLLeftHoldable;
            @LLeftHoldable.canceled -= instance.OnLLeftHoldable;
            @LDownHoldable.started -= instance.OnLDownHoldable;
            @LDownHoldable.performed -= instance.OnLDownHoldable;
            @LDownHoldable.canceled -= instance.OnLDownHoldable;
            @LRightHoldable.started -= instance.OnLRightHoldable;
            @LRightHoldable.performed -= instance.OnLRightHoldable;
            @LRightHoldable.canceled -= instance.OnLRightHoldable;
            @RUpHoldable.started -= instance.OnRUpHoldable;
            @RUpHoldable.performed -= instance.OnRUpHoldable;
            @RUpHoldable.canceled -= instance.OnRUpHoldable;
            @RLeftHoldable.started -= instance.OnRLeftHoldable;
            @RLeftHoldable.performed -= instance.OnRLeftHoldable;
            @RLeftHoldable.canceled -= instance.OnRLeftHoldable;
            @RDownHoldable.started -= instance.OnRDownHoldable;
            @RDownHoldable.performed -= instance.OnRDownHoldable;
            @RDownHoldable.canceled -= instance.OnRDownHoldable;
            @RRightHoldable.started -= instance.OnRRightHoldable;
            @RRightHoldable.performed -= instance.OnRRightHoldable;
            @RRightHoldable.canceled -= instance.OnRRightHoldable;
            @LClick.started -= instance.OnLClick;
            @LClick.performed -= instance.OnLClick;
            @LClick.canceled -= instance.OnLClick;
            @Space.started -= instance.OnSpace;
            @Space.performed -= instance.OnSpace;
            @Space.canceled -= instance.OnSpace;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayersActions.UnregisterCallbacks(IPlayersActions)" />.
        /// </summary>
        /// <seealso cref="PlayersActions.UnregisterCallbacks(IPlayersActions)" />
        public void RemoveCallbacks(IPlayersActions instance)
        {
            if (m_Wrapper.m_PlayersActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayersActions.AddCallbacks(IPlayersActions)" />
        /// <seealso cref="PlayersActions.RemoveCallbacks(IPlayersActions)" />
        /// <seealso cref="PlayersActions.UnregisterCallbacks(IPlayersActions)" />
        public void SetCallbacks(IPlayersActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayersActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayersActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayersActions" /> instance referencing this action map.
    /// </summary>
    public PlayersActions @Players => new PlayersActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Players" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayersActions.AddCallbacks(IPlayersActions)" />
    /// <seealso cref="PlayersActions.RemoveCallbacks(IPlayersActions)" />
    public interface IPlayersActions
    {
        /// <summary>
        /// Method invoked when associated input action "Test" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LMov" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLMov(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RMov" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRMov(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EjeX" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEjeX(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EjeY" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEjeY(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRDown(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LUpHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLUpHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LLeftHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLLeftHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LDownHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLDownHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LRightHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLRightHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RUpHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRUpHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RLeftHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRLeftHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RDownHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRDownHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RRightHoldable" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRRightHoldable(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Space" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSpace(InputAction.CallbackContext context);
    }
}
